### ISSUE TITLE
Publish on MELPA

### ISSUE THREAD

**Issue by cjbassi** [Alexander-Miller/i3wm-Config-Mode#1]
Is this published to melpa? If not, do you think that's something you would be open to doing? Thanks!

**Comment by Alexander-Miller** [comment]
Maybe. I've had plans to, the readme wouldn't be there otherwise, but the
package is in a fairly hacky condition that I was never satisfied with, so I
only ever used it myself.

I've the time for a rewrite now, if that goes well I'll put it on MELPA.

**Comment by Alexander-Miller** [comment]
There we go https://github.com/melpa/melpa/pull/7157
