### ISSUE TITLE
Hexadecimal colors look like comments

### ISSUE THREAD

**Issue by tastytea** [Alexander-Miller/i3wm-Config-Mode#3]
Colors are specified as hexadecimal values with a `#` in front.<sup>1,2</sup> Currently they look like comments. An easy workaround is to use [rainbow-mode](https://elpa.gnu.org/packages/rainbow-mode.html).

![screenshot_i3wm-config-mode_hexcolors](https://user-images.githubusercontent.com/3681516/96034441-d69a8700-0e61-11eb-93cb-389e9fd8627c.png)

¹ <https://i3wm.org/docs/userguide.html#_changing_colors>
² <https://i3wm.org/docs/userguide.html#_colors>

**Comment by Alexander-Miller** [comment]
> An easy workaround is to use rainbow-mode.

I use rainbow-mode, which is why I never even noticed that colours look like comments without out. I have included a reference for it in the readme now.
