### ISSUE TITLE
Support set_from_resource

### ISSUE THREAD

**Issue by sheijk** [Alexander-Miller/i3wm-Config-Mode#4]
See section 4.16. in the [user guide](https://i3wm.org/docs/userguide.html)

Also nice plugin, thanks for writing it :)

**Comment by Alexander-Miller** [comment]
Should work now. Let me know if I missed something.

**Comment by sheijk** [comment]
There seems to be a typo, in the source it's "set_from_resources" but should be "set_from_resource" (singular). Apart from that it works

**Comment by Alexander-Miller** [comment]
Typo is taken care of now.

**Comment by sheijk** [comment]
Works great, thanks for the quick fix :)
