### ISSUE TITLE
Auto-indent flattening indented blocks

### ISSUE THREAD

**Issue by duncan-bayne** [Alexander-Miller/i3wm-Config-Mode#6]
Hi - thanks for i3wm-Config-Mode :) 

I'm seeing some odd behaviour, though, when trying to auto-indent.  When I start with an indented config block like this:

```
# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
	status_command i3status
}
```

After auto-indenting, it becomes:

```
# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
status_command i3status
}
```

### versions

* Linux Mint 21.2
* GNU Emacs 29.1
* i3wm-config-mode 20220913.1121

**Comment by Alexander-Miller** [comment]
All i3wm-config-mode does is add syntax highlighting. Other than that it just extends from conf-mode. Unless there is a better mode to extend from there is nothing I can do here.
